### ISSUE TITLE
Catalogue Error getting sourcePackage

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#55]
I having this error:

```
17:20:28,717 I       BrokerConfig File 'brokerconf.json' doesn't exist.
17:20:28,719 I    CatalogueBroker Catalogue Broker Version 1.4.0
17:20:28,728 I    CatalogueBroker Starting Catalogue Broker with: {
  "host": "0.0.0.0",
  "coapHost": "0.0.0.0",
  "keystorePath": "/opt/reTHINK/catalogue/ssl/keystore",
  "keystorePassword": "OBF:1vub1vnw1shm1y851vgl1vg91y7t1shw1vn61vuz",
  "truststorePath": "/opt/reTHINK/catalogue/ssl/keystore",
  "truststorePassword": "OBF:1vub1vnw1shm1y851vgl1vg91y7t1shw1vn61vuz",
  "keystoreManagerPassword": "OBF:1vub1vnw1shm1y851vgl1vg91y7t1shw1vn61vuz",
  "httpPort": 80,
  "httpsPort": 443,
  "coapPort": 5683,
  "coapsPort": 5684,
  "logLevel": 3,
  "defaultDescriptors": {}
}
17:20:28,920 I    CatalogueBroker Starting CoAP Server...
17:20:29,097 I   WellKnownServlet WellKnownServlet started
17:20:29,102 I       EventServlet EventServlet started
17:20:29,103 I    CatalogueBroker Starting HTTP Server...
17:20:29,418 I    CatalogueBroker Catalogue Broker started
17:21:49,838 I     RequestHandler 'DB_0216047519' registered
17:21:59,897 W     RequestHandler Could not find instance: BraceletSensorObserver_sp
17:22:03,433 W     RequestHandler Could not find instance: BraceletSensorObserver_sp
```

But the database was running well:
![screenshot from 2017-01-05 17-23-34](https://cloud.githubusercontent.com/assets/10596749/21690479/5f9e183a-d36c-11e6-89e0-4c7f3c0febc3.png)

The commands i ran:

```shell
docker run -it -d --name="catalogue-broker" --net=host --expose=433 rethink/catalogue-broker
docker run -it -d --net=host --name="catalogue-database" rethink/catalogue-database-rethinkdefault -host localhost
```
Could help me?

Btw: could see too, why the https://hub.docker.com/r/rethink/catalogue-test-client/builds/ have errors? This docker if only for tests contains the (firstHyperty, secondHyperty, etc) and this make the [tests](https://travis-ci.org/reTHINK-project/dev-service-framework/builds/185525157) on service-framework fail;

Thank you..

**Comment by Endebert** [comment]
@vitormsilva the docker image for `rethink/catalogue-database-rethinkdefault` is still using the old version of the database (i.e. 1.3.2 instead of 1.4.0). This is because `rethink/catalogue-database-rethinkdefault` is based on `rethink/catalogue-database`, but their automated build is triggered at the same time, so `rethink/catalogue-database-rethinkdefault` is always 1 push behind. I just pushed a pseudo commit into the dev branch to trigger a new build, there should be no error with that one.

Regarding `rethink/catalogue-test-client`, it probably fails because there is no catalogue_objects folder in the base directory anymore. I removed it because of issue #46.

**Comment by vitormsilva** [comment]
Ok.. thanks for the reply.

Yes.. but after that we talk with @emmelmann-fokus about have the content of issue #46 running on a separed folder [here](https://github.com/reTHINK-project/dev-catalogue/pull/52) and [here](https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-tests).

The build still failling https://hub.docker.com/r/rethink/catalogue-test-client/builds/, probably some catalogue objects could be outdated, could you do a revision?

**Comment by emmelmann-fokus** [comment]
I try to narrow down the issue:

* The catalogue-test-client docker image is based on catalogue-baseline image.
* the catalogue-baseline images builds correctly on docker hub.
* the catalogue-test-client image is maintained by victor.
* the error message for building the the catalogue-test-client image is as follows:

```
Build failed: The command '/bin/sh -c cd /opt/reTHINK/catalogue/catalogue_objects' returned a non-zero code: 2
```

Note: this message can be retrieved by going to https://hub.docker.com/r/rethink/catalogue-test-client/builds/ and clicking on the entry ```!Error```

* This error message seems to belong to the following code in the catalogue-test-client image:

```
# just assure that the database and default objects are installed.
RUN cd /opt/reTHINK/catalogue/catalogue_objects
```

* checking the baseline image now:

```docker run -it --rm --entrypoint /bin/bash rethink/catalogue-database```

and then 

```
$ cd /opt/reTHINK/catalogue

$ ls -l 

total 56
-rw-r--r-- 1 root root  719 Dec 22 15:22 Dockerfile
-rw-r--r-- 1 root root  624 Dec 22 15:22 License.txt
-rw-r--r-- 1 root root  898 Dec 22 15:22 README.md
drwxr-xr-x 4 root root 4096 Dec 22 15:22 catalogue_broker
drwxr-xr-x 5 root root 4096 Dec 22 15:23 catalogue_database
drwxr-xr-x 5 root root 4096 Dec 22 15:22 doc
drwxr-xr-x 8 root root 4096 Dec 22 15:22 docker
drwxr-xr-x 2 root root 4096 Dec 22 15:22 example_configurations
drwxr-xr-x 2 root root 4096 Dec 22 15:22 model
-rw-r--r-- 1 root root 5062 Dec 22 15:22 pom.xml
drwxr-xr-x 2 root root 4096 Dec 22 15:22 ssl
-rw-r--r-- 1 root root 6277 Dec 22 15:22 version_history.md

```

Reveals that there is no subdirectory catalogue_objects.

This is actually expected behavior, as we decided that the catalogue objects should not be part of the actual development repo but should be included by each deployment.  If I remember that was the quick fix due to catalogue objects that were introduced without following the specification, i.e. without providing a globally unique ID in the object, which caused two objects having the same id.

Anyway, if you look at the docker file for rethink/catalogue-database-rethinkdefault, you see how to correctly create a deployment of a catalogue database.

This was the long version of @Endebert correct answer to the issue.  Please nail down and correct with errors in the docker file that builds the catalogue-test-client first.  

Regarding the issue with dependencies between images and git commits:  once the code is stable, having this dependency is not an issue; in fact, having the derivation of deployments on rethink/catalogue-database makes is efficient as it assures that you always have the latest version of the catalogue code as the catalogue objects should and will not be kept in the same repository as the actual catalogue code.

If this is an issue for your specific image, do not base it on rethink/catalogue-database but on rethink/catalogue-baseline.  But then you have to include and maintain / update all that is provided by rethink/catalogue-database.

**Comment by emmelmann-fokus** [comment]
Closing this issue as it seems it relates to errors in the catalogue-test-client docker file and not the catalogue code.

Please reopen if we encounter errors in the catalogue code.
